[package]
name = "client"
version = "0.4.6"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log4rs = "1"
parking_lot = "0.12"
chrono = "0.4"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
crossbeam-channel = "0.5"
rand = "0.8"
common = {path = "../common"}
abs_tun = {path = "../abs_tun"}