[package]
name = "common"
version = "0.4.6"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

[dependencies]
ahash = "0.8"
anyhow = "1"
md5 = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
socket2 = "0.4"
tokio = { version = "1", features = ["full"] }