[package]
name = "server"
version = "0.4.6"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}