[package]
name = "cli"
version = "0.4.6"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
anyhow = "1"
log4rs = "1"
client = {path = "../client"}
server = {path = "../server"}
abs_tun = {path = "../abs_tun"}
common = {path = "../common"}
mimalloc = { version = "*", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1